// Catalogue Skyalys — FICHIER GENERE (voir scripts/gen_catalog.py).
// Prix HT, cales sur la reference marche lorsque connus. Les champs chimiques
// (CAS, formule, masse molaire, PubChem) doivent etre verifies contre le COA
// du fournisseur avant publication ; un champ null n'est pas affiche.

export type CategorySlug =
  | "metabolique"
  | "myo-science"
  | "recherche-tissulaire"
  | "nootropiques"
  | "longevite"
  | "skin-science"
  | "consommables";

export type Format = "lyophilise" | "solution" | "consommable";

export type Category = { slug: CategorySlug; name: string; short: string; description: string };
export type Variant = { label: string; sku: string; price: number };
export type Reference = { title: string; source: string; url: string };

export type Product = {
  slug: string;
  name: string;
  category: CategorySlug;
  format: Format;
  summary: string;
  synonyms: string[];
  cas: string | null;
  formula: string | null;
  molarMass: number | null;
  pubchem: string | null;
  purity: string;
  appearance: string;
  storage: string;
  variants: Variant[];
  mechanism: string;
  researchAreas: string[];
  faqs: { q: string; a: string }[];
  references: Reference[];
  isNew?: boolean;
  featured?: boolean;
  regulated?: boolean;
  quoteOnly?: boolean;
};

export const categories: Category[] = [
  { slug: "metabolique", name: "Métabolique", short: "Incrétines, amyline, AMPK", description: "Agonistes des récepteurs incrétines, analogues de l’amyline et activateurs métaboliques pour l’étude de la signalisation GLP-1 / GIP / glucagon et de l’homéostasie énergétique in vitro." },
  { slug: "myo-science", name: "Myo-Science", short: "Axe GH / IGF-1, muscle", description: "Sécrétagogues de l’hormone de croissance, facteurs de croissance et modulateurs de la myostatine pour l’étude de l’axe GH / IGF-1 et du développement tissulaire." },
  { slug: "recherche-tissulaire", name: "Recherche Tissulaire", short: "Réparation, angiogenèse", description: "Peptides étudiés dans les modèles de migration cellulaire, d’angiogenèse, de cicatrisation, d’immunomodulation et de réparation tissulaire." },
  { slug: "nootropiques", name: "Nootropiques", short: "Cognition, stress, sommeil", description: "Neuropeptides et analogues étudiés dans la neuroprotection, les facteurs neurotrophiques, le sommeil et la régulation du stress dans des modèles précliniques." },
  { slug: "longevite", name: "Longévité", short: "Mitochondries, NAD+, sénescence", description: "Composés étudiés dans la biologie du vieillissement : fonction mitochondriale, métabolisme du NAD+, télomères, axes hormonaux et sénescence cellulaire." },
  { slug: "skin-science", name: "Skin Science", short: "Matrice, collagène, pigmentation", description: "Peptides de recherche pour les modèles cutanés : synthèse de matrice extracellulaire, fibroblastes, kératinocytes, pigmentation et formulation cosmétique." },
  { slug: "consommables", name: "Consommables", short: "Solvants, flacons, stockage", description: "Solvants de reconstitution, flacons et matériel de stockage pour la préparation et la conservation des peptides au laboratoire." },
];

export const formats: { slug: Format; name: string }[] = [
  { slug: "lyophilise", name: "Lyophilisé" },
  { slug: "solution", name: "Solution" },
  { slug: "consommable", name: "Consommable" },
];

const LYO = "Poudre lyophilisée : −20 °C, à l’abri de la lumière et de l’humidité. Après reconstitution : 2 à 8 °C, aliquoter pour éviter les cycles de congélation et décongélation.";
const SOL = "Conserver à 2 à 8 °C, à l’abri de la lumière. Ne pas congeler sauf indication contraire.";

const pubchemSearch = (t: string): Reference => ({
  title: `Fiche composé : ${t}`,
  source: "PubChem, National Library of Medicine",
  url: `https://pubchem.ncbi.nlm.nih.gov/#query=${encodeURIComponent(t)}`,
});
const pubmedSearch = (t: string): Reference => ({
  title: `Publications indexées : ${t}`,
  source: "PubMed, National Library of Medicine",
  url: `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(t)}`,
});

const standardFaqs = (name: string) => [
  {
    q: `Comment le lot de ${name} est-il contrôlé ?`,
    a: "Chaque lot est contrôlé par HPLC (pureté relative) et par spectrométrie de masse (identité moléculaire). Le certificat d’analyse du lot expédié est disponible dans l’espace Analyses et joint à la commande.",
  },
  {
    q: "Le pourcentage HPLC garantit-il la quantité contenue dans le flacon ?",
    a: "Non. La HPLC mesure la proportion du pic principal dans les conditions de la méthode. La quantité nette dépend aussi de la teneur en eau et en contre-ions. Pour un dosage précis, prévoir une quantification complémentaire.",
  },
  {
    q: "Ce produit peut-il être utilisé chez l’homme ou l’animal ?",
    a: "Non. Il est vendu exclusivement pour la recherche in vitro et les usages analytiques. Toute commande implique l’acceptation de cette restriction.",
  },
];

export const products: Product[] = [
  {
    slug: "retatrutide", name: "Retatrutide", category: "metabolique", format: "lyophilise",
    summary: "Triple agoniste des récepteurs GIP, GLP-1 et glucagon, destiné à la pharmacologie comparative des incrétines in vitro.",
    synonyms: ["LY3437943"], cas: '2381089-83-2', formula: 'C221H342N46O68', molarMass: 4731.33, pubchem: '171390338',
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-RETATRUTIDE-5MG", price: 54.99 }, { label: "10 mg", sku: "SKY-RETATRUTIDE-10MG", price: 94.99 }, { label: "15 mg", sku: "SKY-RETATRUTIDE-15MG", price: 129.99 }, { label: "20 mg", sku: "SKY-RETATRUTIDE-20MG", price: 154.99 }, { label: "30 mg", sku: "SKY-RETATRUTIDE-30MG", price: 214.99 }, { label: "40 mg", sku: "SKY-RETATRUTIDE-40MG", price: 254.99 }, { label: "50 mg", sku: "SKY-RETATRUTIDE-50MG", price: 279.99 }, { label: "60 mg", sku: "SKY-RETATRUTIDE-60MG", price: 304.99 }],
    mechanism: "La retatrutide active trois récepteurs couplés aux protéines G (GIPR, GLP-1R, GCGR). L’intérêt expérimental porte sur l’équilibre relatif des trois signaux, leur cinétique et leur dépendance au système cellulaire étudié.",
    researchAreas: ["Pharmacologie comparative des agonistes simples, doubles et triples", "Mesure de l’activation récepteur par récepteur (AMPc, β-arrestine)", "Internalisation et désensibilisation des RCPG", "Modèles cellulaires de l’homéostasie énergétique"],
    faqs: standardFaqs("Retatrutide"),
    references: [{ title: "Triple-Hormone-Receptor Agonist Retatrutide for Obesity: A Phase 2 Trial", source: "Jastreboff et al., NEJM, 2023. DOI : 10.1056/NEJMoa2301972", url: "https://doi.org/10.1056/NEJMoa2301972" }, pubchemSearch("retatrutide")],
    featured: true,
  },
  {
    slug: "tirzepatide", name: "Tirzepatide", category: "metabolique", format: "lyophilise",
    summary: "Double agoniste des récepteurs GIP et GLP-1, référence pour comparer les agonistes incrétines simples, doubles et triples.",
    synonyms: ["LY3298176"], cas: '2023788-19-2', formula: 'C225H348N48O68', molarMass: 4813.45, pubchem: '166567236',
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-TIRZEPATIDE-10MG", price: 64.99 }, { label: "15 mg", sku: "SKY-TIRZEPATIDE-15MG", price: 79.99 }, { label: "20 mg", sku: "SKY-TIRZEPATIDE-20MG", price: 94.99 }, { label: "30 mg", sku: "SKY-TIRZEPATIDE-30MG", price: 134.99 }, { label: "40 mg", sku: "SKY-TIRZEPATIDE-40MG", price: 154.99 }, { label: "50 mg", sku: "SKY-TIRZEPATIDE-50MG", price: 179.99 }, { label: "60 mg", sku: "SKY-TIRZEPATIDE-60MG", price: 204.99 }, { label: "100 mg", sku: "SKY-TIRZEPATIDE-100MG", price: 314.99 }, { label: "120 mg", sku: "SKY-TIRZEPATIDE-120MG", price: 374.99 }],
    mechanism: "La tirzepatide combine une activité agoniste sur GIPR et GLP-1R au sein d’un même peptide acylé. Elle sert de comparateur pour isoler la contribution de chaque récepteur à la signalisation observée.",
    researchAreas: ["Biais de signalisation GIPR / GLP-1R", "Comparaison avec les agonistes sélectifs du GLP-1R", "Études de liaison et de déplacement de ligand"],
    faqs: standardFaqs("Tirzepatide"),
    references: [{ title: "Tirzepatide Once Weekly for the Treatment of Obesity", source: "Jastreboff et al., NEJM, 2022. DOI : 10.1056/NEJMoa2206038", url: "https://doi.org/10.1056/NEJMoa2206038" }, pubchemSearch("tirzepatide")],
    featured: true,
  },
  {
    slug: "semaglutide", name: "Sémaglutide", category: "metabolique", format: "lyophilise",
    summary: "Agoniste sélectif du récepteur GLP-1, contrôle positif de référence pour les essais de signalisation incrétine.",
    synonyms: ["NN9535"], cas: '910463-68-2', formula: 'C187H291N45O59', molarMass: 4113.58, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-SEMAGLUTIDE-10MG", price: 59.99 }, { label: "15 mg", sku: "SKY-SEMAGLUTIDE-15MG", price: 74.99 }, { label: "20 mg", sku: "SKY-SEMAGLUTIDE-20MG", price: 89.99 }, { label: "30 mg", sku: "SKY-SEMAGLUTIDE-30MG", price: 119.99 }],
    mechanism: "Analogue acylé du GLP-1 conçu pour résister à la DPP-4 et se lier à l’albumine. En recherche, il sert de contrôle positif pour l’activation sélective du GLP-1R.",
    researchAreas: ["Contrôle positif des essais GLP-1R", "Stabilité peptidique et acylation", "Liaison à l’albumine et pharmacocinétique préclinique"],
    faqs: standardFaqs("Sémaglutide"),
    references: [pubmedSearch("semaglutide GLP-1"), pubchemSearch("semaglutide")],
  },
  {
    slug: "mazdutide", name: "Mazdutide", category: "metabolique", format: "lyophilise",
    summary: "Double agoniste des récepteurs GLP-1 et glucagon, étudié dans la signalisation métabolique comparée.",
    synonyms: ["IBI362", "LY3305677"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-MAZDUTIDE-10MG", price: 99.99 }],
    mechanism: "La mazdutide active conjointement GLP-1R et GCGR. La recherche compare son profil à celui des agonistes GLP-1 seuls et des triples agonistes.",
    researchAreas: ["Co-activation GLP-1R / GCGR", "Dépense énergétique en modèle cellulaire", "Comparaison inter-agonistes"],
    faqs: standardFaqs("Mazdutide"),
    references: [pubmedSearch("mazdutide")],
    isNew: true,
  },
  {
    slug: "liraglutide", name: "Liraglutide", category: "metabolique", format: "lyophilise",
    summary: "Agoniste du récepteur GLP-1 à action prolongée, comparateur historique des analogues incrétines.",
    synonyms: [], cas: '204656-20-2', formula: 'C172H265N43O51', molarMass: 3751.2, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-LIRAGLUTIDE-5MG", price: 49.99 }, { label: "10 mg", sku: "SKY-LIRAGLUTIDE-10MG", price: 84.99 }, { label: "30 mg", sku: "SKY-LIRAGLUTIDE-30MG", price: 199.99 }],
    mechanism: "Analogue acylé du GLP-1 lié à l’albumine. Utilisé comme comparateur de première génération dans les études de signalisation incrétine.",
    researchAreas: ["Comparateur GLP-1R", "Acylation et demi-vie", "Signalisation AMPc"],
    faqs: standardFaqs("Liraglutide"),
    references: [pubmedSearch("liraglutide GLP-1"), pubchemSearch("liraglutide")],
    regulated: true,
  },
  {
    slug: "cagrilintide", name: "Cagrilintide", category: "metabolique", format: "lyophilise",
    summary: "Analogue acylé de l’amyline à longue durée d’action, pour l’étude du second axe de la signalisation métabolique.",
    synonyms: ["NN9838"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-CAGRILINTIDE-5MG", price: 79.99 }, { label: "10 mg", sku: "SKY-CAGRILINTIDE-10MG", price: 129.99 }],
    mechanism: "La cagrilintide agit sur les récepteurs de l’amyline et de la calcitonine (complexes CTR / RAMP), une voie distincte des incrétines.",
    researchAreas: ["Pharmacologie des récepteurs AMY1 à AMY3", "Associations amyline et GLP-1 en modèle cellulaire", "Sélectivité CTR / RAMP"],
    faqs: standardFaqs("Cagrilintide"),
    references: [pubmedSearch("cagrilintide amylin"), pubchemSearch("cagrilintide")],
    isNew: true,
  },
  {
    slug: "aod-9604", name: "AOD-9604", category: "metabolique", format: "lyophilise",
    summary: "Fragment modifié de l’hormone de croissance (176-191), étudié dans le métabolisme lipidique in vitro.",
    synonyms: ["AOD9604"], cas: '221231-10-3', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-AOD-9604-2MG", price: 49.99 }, { label: "5 mg", sku: "SKY-AOD-9604-5MG", price: 84.99 }, { label: "10 mg", sku: "SKY-AOD-9604-10MG", price: 139.99 }],
    mechanism: "L’AOD-9604 reprend la région C-terminale de la GH. Il est étudié pour son influence sur la lipolyse et la lipogenèse dans des modèles adipocytaires, sans l’activité somatotrope de la GH entière.",
    researchAreas: ["Lipolyse et lipogenèse en adipocytes", "Fragments de la GH", "Métabolisme lipidique"],
    faqs: standardFaqs("AOD-9604"),
    references: [pubmedSearch("AOD9604"), pubchemSearch("AOD9604")],
  },
  {
    slug: "5-amino-1mq", name: "5-Amino-1MQ", category: "metabolique", format: "lyophilise",
    summary: "Inhibiteur sélectif de la NNMT, étudié dans le métabolisme énergétique des adipocytes.",
    synonyms: [], cas: '100130-61-4', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-5-AMINO-1MQ-5MG", price: 34.99 }, { label: "10 mg", sku: "SKY-5-AMINO-1MQ-10MG", price: 54.99 }, { label: "50 mg", sku: "SKY-5-AMINO-1MQ-50MG", price: 134.99 }],
    mechanism: "Le 5-Amino-1MQ inhibe la nicotinamide N-méthyltransférase (NNMT). La recherche étudie son effet sur le pool de NAD+ et la dépense énergétique adipocytaire.",
    researchAreas: ["Inhibition de la NNMT", "Pool de NAD+ et SAM", "Différenciation adipocytaire"],
    faqs: standardFaqs("5-Amino-1MQ"),
    references: [pubmedSearch("5-Amino-1MQ NNMT")],
    isNew: true,
  },
  {
    slug: "aicar", name: "AICAR", category: "metabolique", format: "lyophilise",
    summary: "Activateur de l’AMPK perméable aux cellules, outil classique pour moduler le métabolisme énergétique in vitro.",
    synonyms: ["Acadésine", "AICA riboside"], cas: '2627-69-2', formula: 'C9H14N4O5', molarMass: 258.23, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "50 mg", sku: "SKY-AICAR-50MG", price: 64.99 }, { label: "100 mg", sku: "SKY-AICAR-100MG", price: 109.99 }],
    mechanism: "Une fois phosphorylé en ZMP, l’AICAR mime l’AMP et active l’AMPK. Outil pharmacologique de référence pour l’étude du métabolisme glucidique et lipidique.",
    researchAreas: ["Activation de l’AMPK", "Captation du glucose et oxydation des acides gras", "Biogenèse mitochondriale"],
    faqs: standardFaqs("AICAR"),
    references: [pubmedSearch("AICAR AMPK"), pubchemSearch("acadesine")],
  },
  {
    slug: "slu-pp-332", name: "SLU-PP-332", category: "metabolique", format: "lyophilise",
    summary: "Agoniste pan-ERR, étudié comme mimétique de l’exercice dans le métabolisme oxydatif.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-SLU-PP-332-5MG", price: 34.99 }, { label: "10 mg", sku: "SKY-SLU-PP-332-10MG", price: 54.99 }],
    mechanism: "SLU-PP-332 active les récepteurs liés aux œstrogènes (ERRα/β/γ). La recherche l’étudie pour son influence sur le métabolisme oxydatif et la fonction mitochondriale.",
    researchAreas: ["Agonisme ERR", "Métabolisme oxydatif", "Mimétiques de l’exercice"],
    faqs: standardFaqs("SLU-PP-332"),
    references: [pubmedSearch("SLU-PP-332 ERR")],
    isNew: true,
  },
  {
    slug: "adipotide", name: "Adipotide", category: "metabolique", format: "lyophilise",
    summary: "Peptide proapoptotique ciblant la vascularisation du tissu adipeux, étudié en modèle préclinique.",
    synonyms: ["FTPP", "Prohibitin-TP01"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-ADIPOTIDE-2MG", price: 39.99 }, { label: "5 mg", sku: "SKY-ADIPOTIDE-5MG", price: 69.99 }, { label: "10 mg", sku: "SKY-ADIPOTIDE-10MG", price: 109.99 }],
    mechanism: "L’adipotide cible la prohibitine de la vascularisation du tissu adipeux blanc et induit l’apoptose endothéliale dans des modèles précliniques.",
    researchAreas: ["Ciblage vasculaire du tissu adipeux", "Apoptose endothéliale", "Modèles précliniques d’obésité"],
    faqs: standardFaqs("Adipotide"),
    references: [pubmedSearch("adipotide prohibitin")],
  },
  {
    slug: "l-carnitine", name: "L-Carnitine", category: "metabolique", format: "solution",
    summary: "Transporteur d’acides gras vers la mitochondrie, réactif d’étude du métabolisme énergétique.",
    synonyms: ["Lévocarnitine"], cas: '541-15-1', formula: 'C7H15NO3', molarMass: 161.2, pubchem: null,
    purity: "Qualité laboratoire", appearance: "Solution limpide", storage: SOL,
    variants: [{ label: "200 mg", sku: "SKY-L-CARNITINE-200MG", price: 24.99 }, { label: "400 mg", sku: "SKY-L-CARNITINE-400MG", price: 34.99 }, { label: "600 mg", sku: "SKY-L-CARNITINE-600MG", price: 44.99 }, { label: "1200 mg", sku: "SKY-L-CARNITINE-1200MG", price: 69.99 }],
    mechanism: "La L-carnitine permet le transport des acides gras à longue chaîne dans la mitochondrie via la navette carnitine. Réactif d’étude de la β-oxydation.",
    researchAreas: ["β-oxydation mitochondriale", "Navette carnitine (CPT1/CPT2)", "Bioénergétique cellulaire"],
    faqs: standardFaqs("L-Carnitine"),
    references: [pubchemSearch("L-carnitine")],
  },
  {
    slug: "lipo-c", name: "Lipo-C", category: "metabolique", format: "solution",
    summary: "Formulation lipotrope de recherche combinant des agents méthyl-donneurs.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "Qualité laboratoire", appearance: "Solution limpide", storage: SOL,
    variants: [{ label: "10 ml", sku: "SKY-LIPO-C-10ML", price: 39.99 }],
    mechanism: "Mélange lipotrope associant méthionine, inositol et choline. Étudié dans les modèles de métabolisme hépatique des lipides.",
    researchAreas: ["Métabolisme hépatique des lipides", "Agents méthyl-donneurs", "Transport des lipides"],
    faqs: standardFaqs("Lipo-C"),
    references: [pubmedSearch("methionine inositol choline lipotropic")],
  },
  {
    slug: "mic-b12", name: "MIC (Lipo-C + B12)", category: "metabolique", format: "solution",
    summary: "Formulation lipotrope de recherche enrichie en vitamine B12.",
    synonyms: ["Lipo C with B12"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "Qualité laboratoire", appearance: "Solution limpide", storage: SOL,
    variants: [{ label: "10 ml", sku: "SKY-MIC-B12-10ML", price: 44.99 }],
    mechanism: "Association méthionine-inositol-choline complétée par la cyanocobalamine (B12), étudiée dans le métabolisme énergétique et lipidique.",
    researchAreas: ["Métabolisme lipidique", "Cofacteurs B12", "Agents méthyl-donneurs"],
    faqs: standardFaqs("MIC (Lipo-C + B12)"),
    references: [pubmedSearch("lipotropic B12 methionine inositol choline")],
  },
  {
    slug: "hgh", name: "HGH (somatropine)", category: "myo-science", format: "lyophilise",
    summary: "Hormone de croissance recombinante. Référence réglementée, disponible uniquement sur devis à des structures autorisées.",
    synonyms: ["Somatropine", "Hormone de croissance"], cas: '12629-01-5', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 iu", sku: "SKY-HGH-10IU", price: 0 }, { label: "12 iu", sku: "SKY-HGH-12IU", price: 0 }, { label: "15 iu", sku: "SKY-HGH-15IU", price: 0 }, { label: "24 iu", sku: "SKY-HGH-24IU", price: 0 }, { label: "36 iu", sku: "SKY-HGH-36IU", price: 0 }],
    mechanism: "La somatropine se lie au récepteur de la GH et déclenche la voie JAK2/STAT5 et la production hépatique d’IGF-1. Produit pharmaceutique strictement réglementé.",
    researchAreas: ["Axe GH / IGF-1", "Signalisation JAK2/STAT5", "Études sur récepteur de la GH"],
    faqs: standardFaqs("HGH (somatropine)"),
    references: [pubmedSearch("growth hormone JAK2 STAT5")],
    regulated: true, quoteOnly: true,
  },
  {
    slug: "hgh-fragment-176-191", name: "HGH Fragment 176-191", category: "myo-science", format: "lyophilise",
    summary: "Fragment C-terminal de l’hormone de croissance, étudié dans le métabolisme lipidique.",
    synonyms: ["HGH Frag 176-191"], cas: '66004-57-7', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-HGH-FRAGMENT-176-191-5MG", price: 54.99 }, { label: "10 mg", sku: "SKY-HGH-FRAGMENT-176-191-10MG", price: 89.99 }],
    mechanism: "Ce fragment reprend la région 176-191 de la GH. Il est étudié pour son action sur la lipolyse sans l’activité de croissance de la GH entière.",
    researchAreas: ["Lipolyse adipocytaire", "Fragments de la GH", "Métabolisme lipidique"],
    faqs: standardFaqs("HGH Fragment 176-191"),
    references: [pubmedSearch("growth hormone fragment 176-191")],
  },
  {
    slug: "frag-17-23", name: "Frag 17-23", category: "myo-science", format: "lyophilise",
    summary: "Court fragment peptidique dérivé de la GH, utilisé en recherche métabolique.",
    synonyms: ["HGH 17-23"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-FRAG-17-23-10MG", price: 49.99 }],
    mechanism: "Fragment synthétique court dérivé de la séquence de l’hormone de croissance, étudié dans des modèles métaboliques.",
    researchAreas: ["Fragments de la GH", "Études de structure-activité", "Métabolisme lipidique"],
    faqs: standardFaqs("Frag 17-23"),
    references: [pubmedSearch("growth hormone peptide fragment")],
  },
  {
    slug: "sermorelin", name: "Sermorelin Acetate", category: "myo-science", format: "lyophilise",
    summary: "Analogue du GHRH (1-29), sécrétagogue étudié dans l’axe GH / IGF-1.",
    synonyms: ["GRF 1-29"], cas: '86168-78-7', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-SERMORELIN-5MG", price: 44.99 }, { label: "10 mg", sku: "SKY-SERMORELIN-10MG", price: 69.99 }],
    mechanism: "La sermorélin reprend les 29 premiers acides aminés du GHRH et stimule le récepteur du GHRH sur les cellules somatotropes dans des modèles d’étude de l’axe GH.",
    researchAreas: ["Récepteur du GHRH", "Sécrétion pulsatile de GH", "Axe GH / IGF-1"],
    faqs: standardFaqs("Sermorelin Acetate"),
    references: [pubmedSearch("sermorelin GHRH"), pubchemSearch("sermorelin")],
  },
  {
    slug: "tesamorelin", name: "Tesamorelin", category: "myo-science", format: "lyophilise",
    summary: "Analogue stabilisé du GHRH, étudié dans l’axe GH / IGF-1 et le métabolisme lipidique.",
    synonyms: [], cas: '218949-48-5', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-TESAMORELIN-2MG", price: 39.99 }, { label: "5 mg", sku: "SKY-TESAMORELIN-5MG", price: 59.99 }, { label: "10 mg", sku: "SKY-TESAMORELIN-10MG", price: 79.99 }, { label: "20 mg", sku: "SKY-TESAMORELIN-20MG", price: 139.99 }],
    mechanism: "La tésamoréline est un analogue du GHRH stabilisé par un groupement trans-3-hexénoyl. Elle est étudiée pour son action sur la sécrétion de GH et le tissu adipeux viscéral.",
    researchAreas: ["Récepteur du GHRH", "Tissu adipeux viscéral", "Axe GH / IGF-1"],
    faqs: standardFaqs("Tesamorelin"),
    references: [pubmedSearch("tesamorelin GHRH"), pubchemSearch("tesamorelin")],
  },
  {
    slug: "cjc-1295-dac", name: "CJC-1295 (with DAC)", category: "myo-science", format: "lyophilise",
    summary: "Analogue du GHRH à demi-vie prolongée par liaison à l’albumine (DAC).",
    synonyms: [], cas: '863288-34-0', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-CJC-1295-DAC-2MG", price: 59.99 }, { label: "5 mg", sku: "SKY-CJC-1295-DAC-5MG", price: 99.99 }],
    mechanism: "Le CJC-1295 avec DAC se lie de façon covalente à l’albumine, prolongeant son action sur le récepteur du GHRH dans les modèles de sécrétion de GH.",
    researchAreas: ["Récepteur du GHRH", "Liaison à l’albumine (DAC)", "Cinétique de sécrétion de GH"],
    faqs: standardFaqs("CJC-1295 (with DAC)"),
    references: [pubmedSearch("CJC-1295 DAC GHRH")],
  },
  {
    slug: "cjc-1295-no-dac", name: "CJC-1295 (no DAC)", category: "myo-science", format: "lyophilise",
    summary: "Analogue du GHRH (modified GRF 1-29) à action courte, sans DAC.",
    synonyms: ["Mod GRF 1-29"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-CJC-1295-NO-DAC-2MG", price: 44.99 }, { label: "5 mg", sku: "SKY-CJC-1295-NO-DAC-5MG", price: 69.99 }],
    mechanism: "Le CJC-1295 sans DAC est un GRF 1-29 modifié, étudié en association avec les sécrétagogues de type ghréline pour la sécrétion pulsatile de GH.",
    researchAreas: ["Récepteur du GHRH", "Synergie GHRH / ghréline", "Sécrétion pulsatile de GH"],
    faqs: standardFaqs("CJC-1295 (no DAC)"),
    references: [pubmedSearch("CJC-1295 GHRH")],
  },
  {
    slug: "cjc-1295-ipamorelin", name: "CJC-1295 (no DAC) + Ipamorelin", category: "myo-science", format: "lyophilise",
    summary: "Association d’un analogue du GHRH et d’un sécrétagogue sélectif, étudiée pour la synergie sur l’axe GH.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg (5+5)", sku: "SKY-CJC-1295-IPAMORELIN-10MG55", price: 74.99 }],
    mechanism: "Combinaison d’un GRF 1-29 modifié et de l’ipamoréline (agoniste du récepteur de la ghréline). La recherche étudie la synergie des deux voies sur la sécrétion de GH.",
    researchAreas: ["Synergie GHRH / récepteur de la ghréline", "Sécrétion pulsatile de GH", "Combinaisons de sécrétagogues"],
    faqs: standardFaqs("CJC-1295 (no DAC) + Ipamorelin"),
    references: [pubmedSearch("CJC-1295 ipamorelin growth hormone")],
    isNew: true,
  },
  {
    slug: "ipamorelin", name: "Ipamorelin", category: "myo-science", format: "lyophilise",
    summary: "Agoniste sélectif du récepteur de la ghréline (GHS-R), sécrétagogue de référence.",
    synonyms: [], cas: '170851-70-4', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-IPAMORELIN-2MG", price: 39.99 }, { label: "5 mg", sku: "SKY-IPAMORELIN-5MG", price: 49.99 }, { label: "10 mg", sku: "SKY-IPAMORELIN-10MG", price: 64.99 }],
    mechanism: "L’ipamoréline active sélectivement le récepteur de la ghréline (GHS-R1a) avec peu d’effet sur le cortisol et la prolactine, ce qui en fait un outil propre pour étudier cette voie.",
    researchAreas: ["Récepteur de la ghréline (GHS-R1a)", "Sélectivité des sécrétagogues", "Sécrétion de GH"],
    faqs: standardFaqs("Ipamorelin"),
    references: [pubmedSearch("ipamorelin ghrelin receptor"), pubchemSearch("ipamorelin")],
  },
  {
    slug: "ghrp-2", name: "GHRP-2", category: "myo-science", format: "lyophilise",
    summary: "Peptide libérateur de GH, agoniste du récepteur de la ghréline.",
    synonyms: ["Pralmorelin"], cas: '158861-67-7', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-GHRP-2-5MG", price: 34.99 }, { label: "10 mg", sku: "SKY-GHRP-2-10MG", price: 49.99 }, { label: "15 mg", sku: "SKY-GHRP-2-15MG", price: 64.99 }],
    mechanism: "Le GHRP-2 active le récepteur de la ghréline et stimule la sécrétion de GH dans des modèles cellulaires et précliniques.",
    researchAreas: ["Récepteur de la ghréline", "Sécrétion de GH", "Comparaison des GHRP"],
    faqs: standardFaqs("GHRP-2"),
    references: [pubmedSearch("GHRP-2 pralmorelin")],
  },
  {
    slug: "ghrp-6", name: "GHRP-6", category: "myo-science", format: "lyophilise",
    summary: "Peptide libérateur de GH de première génération, agoniste du récepteur de la ghréline.",
    synonyms: [], cas: '87616-84-0', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-GHRP-6-5MG", price: 34.99 }, { label: "10 mg", sku: "SKY-GHRP-6-10MG", price: 49.99 }],
    mechanism: "Le GHRP-6 stimule la sécrétion de GH via le récepteur de la ghréline et augmente l’appétit dans des modèles précliniques.",
    researchAreas: ["Récepteur de la ghréline", "Régulation de l’appétit", "Sécrétion de GH"],
    faqs: standardFaqs("GHRP-6"),
    references: [pubmedSearch("GHRP-6 ghrelin")],
  },
  {
    slug: "hexarelin", name: "Hexarelin Acetate", category: "myo-science", format: "lyophilise",
    summary: "Hexapeptide sécrétagogue de la GH, étudié aussi pour ses effets cardiaques via CD36.",
    synonyms: [], cas: '140703-51-1', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-HEXARELIN-2MG", price: 44.99 }, { label: "5 mg", sku: "SKY-HEXARELIN-5MG", price: 69.99 }],
    mechanism: "L’hexaréline active le récepteur de la ghréline et se lie au récepteur CD36, une voie étudiée dans les modèles cardiovasculaires précliniques.",
    researchAreas: ["Récepteur de la ghréline", "Récepteur CD36", "Modèles cardiovasculaires"],
    faqs: standardFaqs("Hexarelin Acetate"),
    references: [pubmedSearch("hexarelin CD36")],
  },
  {
    slug: "mgf", name: "MGF", category: "myo-science", format: "lyophilise",
    summary: "Facteur de croissance mécanique, variant d’épissage de l’IGF-1 étudié dans la réparation musculaire.",
    synonyms: ["IGF-1Ec"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-MGF-2MG", price: 44.99 }],
    mechanism: "Le MGF est un variant d’épissage de l’IGF-1 exprimé après contrainte mécanique. Il est étudié pour son rôle dans l’activation des cellules satellites musculaires.",
    researchAreas: ["Cellules satellites musculaires", "Variants d’épissage de l’IGF-1", "Réparation musculaire"],
    faqs: standardFaqs("MGF"),
    references: [pubmedSearch("mechano growth factor IGF-1")],
  },
  {
    slug: "peg-mgf", name: "PEG-MGF", category: "myo-science", format: "lyophilise",
    summary: "Forme pégylée du MGF, à stabilité prolongée, pour l’étude de la réparation musculaire.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-PEG-MGF-2MG", price: 69.99 }],
    mechanism: "La pégylation prolonge la stabilité du MGF en solution. Étudié dans les modèles d’activation des cellules satellites et de régénération musculaire.",
    researchAreas: ["Cellules satellites musculaires", "Pégylation et stabilité", "Régénération musculaire"],
    faqs: standardFaqs("PEG-MGF"),
    references: [pubmedSearch("PEG-MGF mechano growth factor")],
    isNew: true,
  },
  {
    slug: "igf-1-lr3", name: "IGF-1 LR3", category: "myo-science", format: "lyophilise",
    summary: "Analogue à longue durée d’action de l’IGF-1, référence des études sur l’axe IGF.",
    synonyms: ["Long R3 IGF-1"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "0.1 mg", sku: "SKY-IGF-1-LR3-01MG", price: 29.99 }, { label: "1 mg", sku: "SKY-IGF-1-LR3-1MG", price: 89.99 }],
    mechanism: "L’IGF-1 LR3 présente une faible affinité pour les protéines de liaison (IGFBP), ce qui prolonge son action sur le récepteur IGF-1R dans les cultures cellulaires.",
    researchAreas: ["Récepteur IGF-1R", "Protéines de liaison (IGFBP)", "Prolifération et différenciation cellulaires"],
    faqs: standardFaqs("IGF-1 LR3"),
    references: [pubmedSearch("IGF-1 LR3")],
    isNew: true,
  },
  {
    slug: "igf-des", name: "IGF-DES", category: "myo-science", format: "lyophilise",
    summary: "Variant tronqué de l’IGF-1 (DES 1-3), à action locale puissante.",
    synonyms: ["DES(1-3) IGF-1"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-IGF-DES-2MG", price: 94.99 }],
    mechanism: "L’IGF-DES est un variant tronqué des trois premiers acides aminés de l’IGF-1, avec une affinité réduite pour les IGFBP et une action locale marquée en culture.",
    researchAreas: ["Récepteur IGF-1R", "Action locale et IGFBP", "Prolifération cellulaire"],
    faqs: standardFaqs("IGF-DES"),
    references: [pubmedSearch("DES(1-3) IGF-1")],
  },
  {
    slug: "follistatin", name: "Follistatin 344", category: "myo-science", format: "lyophilise",
    summary: "Antagoniste de la myostatine, étudié dans la régulation de la masse musculaire.",
    synonyms: ["FST-344"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "1 mg", sku: "SKY-FOLLISTATIN-1MG", price: 149.99 }],
    mechanism: "La follistatine lie et neutralise la myostatine (GDF-8) et d’autres membres de la famille TGF-β, levant leur inhibition sur la croissance musculaire dans les modèles précliniques.",
    researchAreas: ["Inhibition de la myostatine", "Famille TGF-β", "Masse musculaire en modèle préclinique"],
    faqs: standardFaqs("Follistatin 344"),
    references: [pubmedSearch("follistatin myostatin")],
  },
  {
    slug: "ace-031", name: "ACE-031", category: "myo-science", format: "lyophilise",
    summary: "Récepteur leurre de l’activine (ActRIIB-Fc), piégeant la myostatine.",
    synonyms: ["ActRIIB-Fc", "Ramatercept"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "1 mg", sku: "SKY-ACE-031-1MG", price: 149.99 }],
    mechanism: "L’ACE-031 est une protéine de fusion du domaine extracellulaire d’ActRIIB avec un fragment Fc, qui piège la myostatine et l’activine en amont de leur récepteur.",
    researchAreas: ["Piégeage de la myostatine / activine", "Signalisation ActRIIB", "Masse musculaire en modèle préclinique"],
    faqs: standardFaqs("ACE-031"),
    references: [pubmedSearch("ACE-031 ActRIIB myostatin")],
  },
  {
    slug: "gdf-8", name: "GDF-8 (Myostatine)", category: "myo-science", format: "lyophilise",
    summary: "Myostatine recombinante, réactif de référence pour étudier ses antagonistes.",
    synonyms: ["Myostatine"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "1 mg", sku: "SKY-GDF-8-1MG", price: 99.99 }],
    mechanism: "Le GDF-8 (myostatine) est un régulateur négatif de la masse musculaire de la famille TGF-β. Réactif utilisé comme cible dans l’étude de ses inhibiteurs.",
    researchAreas: ["Signalisation de la myostatine", "Famille TGF-β / SMAD", "Cible pour antagonistes"],
    faqs: standardFaqs("GDF-8 (Myostatine)"),
    references: [pubmedSearch("GDF-8 myostatin")],
  },
  {
    slug: "bpc-157", name: "BPC-157", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Pentadécapeptide dérivé d’une protéine gastrique, étudié dans les modèles précliniques de réparation tissulaire.",
    synonyms: ["Body Protection Compound 157", "PL 14736"], cas: '137525-51-0', formula: 'C62H98N16O22', molarMass: 1419.53, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-BPC-157-5MG", price: 39.99 }, { label: "10 mg", sku: "SKY-BPC-157-10MG", price: 64.99 }],
    mechanism: "Le BPC-157 est étudié pour ses effets sur la migration des fibroblastes, l’angiogenèse et la voie du monoxyde d’azote. Les données disponibles sont essentiellement précliniques.",
    researchAreas: ["Migration cellulaire et cicatrisation in vitro", "Angiogenèse (VEGFR2, voie NO)", "Modèles précliniques de lésion tendineuse et digestive"],
    faqs: standardFaqs("BPC-157"),
    references: [pubmedSearch("BPC 157"), pubchemSearch("BPC 157")],
    featured: true,
  },
  {
    slug: "tb-500", name: "TB-500", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Fraction active de la thymosine β4 liant l’actine, étudiée dans la migration cellulaire.",
    synonyms: ["Thymosine β4 fragment", "TB500"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-TB-500-5MG", price: 39.99 }, { label: "10 mg", sku: "SKY-TB-500-10MG", price: 64.99 }],
    mechanism: "Le TB-500 correspond à la région active de la thymosine β4 qui séquestre l’actine-G et régule la dynamique du cytosquelette dans les modèles de migration et de réparation.",
    researchAreas: ["Dynamique de l’actine", "Migration cellulaire", "Modèles de réparation tissulaire"],
    faqs: standardFaqs("TB-500"),
    references: [pubmedSearch("TB-500 thymosin beta 4")],
  },
  {
    slug: "bpc-tb-5", name: "BPC-157 5 mg + TB-500 5 mg", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Association de deux peptides de réparation, étudiée pour leurs effets combinés.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg (5+5)", sku: "SKY-BPC-TB-5-10MG55", price: 79.99 }],
    mechanism: "Association du BPC-157 et du TB-500 étudiée dans les modèles combinant angiogenèse et dynamique de l’actine.",
    researchAreas: ["Combinaisons de peptides de réparation", "Angiogenèse et migration", "Modèles précliniques"],
    faqs: standardFaqs("BPC-157 5 mg + TB-500 5 mg"),
    references: [pubmedSearch("BPC-157 TB-500")],
  },
  {
    slug: "bpc-tb-10", name: "BPC-157 10 mg + TB-500 10 mg", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Association concentrée de deux peptides de réparation pour la recherche.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "20 mg (10+10)", sku: "SKY-BPC-TB-10-20MG1010", price: 120.99 }],
    mechanism: "Version concentrée de l’association BPC-157 et TB-500, étudiée dans les modèles de réparation tissulaire.",
    researchAreas: ["Combinaisons de peptides de réparation", "Angiogenèse et migration", "Modèles précliniques"],
    faqs: standardFaqs("BPC-157 10 mg + TB-500 10 mg"),
    references: [pubmedSearch("BPC-157 TB-500")],
  },
  {
    slug: "ll-37", name: "LL-37", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Peptide antimicrobien de la cathélicidine humaine, étudié en immunité innée et réparation.",
    synonyms: ["Cathélicidine"], cas: '154947-66-7', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-LL-37-5MG", price: 69.99 }],
    mechanism: "Le LL-37 est le fragment actif de la cathélicidine humaine. Il est étudié pour son activité antimicrobienne, son rôle dans l’immunité innée et l’angiogenèse.",
    researchAreas: ["Immunité innée", "Activité antimicrobienne in vitro", "Angiogenèse et réparation"],
    faqs: standardFaqs("LL-37"),
    references: [pubmedSearch("LL-37 cathelicidin")],
    isNew: true,
  },
  {
    slug: "vip", name: "VIP", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Peptide intestinal vasoactif, étudié dans l’immunomodulation et la signalisation neuro-endocrine.",
    synonyms: ["Peptide intestinal vasoactif"], cas: '37221-79-7', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-VIP-5MG", price: 69.99 }, { label: "10 mg", sku: "SKY-VIP-10MG", price: 109.99 }],
    mechanism: "Le VIP active les récepteurs VPAC1/VPAC2 couplés à l’AMPc et module les réponses immunitaires et inflammatoires dans de nombreux modèles cellulaires.",
    researchAreas: ["Récepteurs VPAC1 / VPAC2", "Immunomodulation", "Signalisation AMPc"],
    faqs: standardFaqs("VIP"),
    references: [pubmedSearch("vasoactive intestinal peptide VPAC")],
  },
  {
    slug: "thymosin-alpha-1", name: "Thymosin Alpha-1", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Peptide thymique de 28 acides aminés, étudié dans la modulation immunitaire.",
    synonyms: ["Tα1"], cas: '62304-98-7', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-THYMOSIN-ALPHA-1-5MG", price: 54.99 }, { label: "10 mg", sku: "SKY-THYMOSIN-ALPHA-1-10MG", price: 89.99 }],
    mechanism: "La thymosine α1 module l’activité des cellules dendritiques et des lymphocytes T via les récepteurs de type Toll dans les modèles d’immunité.",
    researchAreas: ["Récepteurs TLR", "Cellules dendritiques et lymphocytes T", "Immunomodulation"],
    faqs: standardFaqs("Thymosin Alpha-1"),
    references: [pubmedSearch("thymosin alpha 1 immune")],
  },
  {
    slug: "thymalin", name: "Thymalin / Thymulin", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Extrait bioregulateur thymique, étudié dans l’homéostasie immunitaire.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-THYMALIN-10MG", price: 59.99 }],
    mechanism: "La thymaline regroupe des peptides thymiques étudiés comme bioregulateurs de la maturation lymphocytaire dans des modèles d’immunosénescence.",
    researchAreas: ["Maturation lymphocytaire", "Bioregulateurs peptidiques", "Immunosénescence"],
    faqs: standardFaqs("Thymalin / Thymulin"),
    references: [pubmedSearch("thymalin thymulin")],
  },
  {
    slug: "cartalax", name: "Cartalax", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Court bioregulateur peptidique (AED), étudié dans le tissu cartilagineux et conjonctif.",
    synonyms: ["AED"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "20 mg", sku: "SKY-CARTALAX-20MG", price: 44.99 }],
    mechanism: "Le cartalax est un tripeptide bioregulateur étudié pour son influence sur l’expression génique dans les modèles de tissu conjonctif et cartilagineux.",
    researchAreas: ["Bioregulateurs peptidiques courts", "Expression génique tissulaire", "Tissu conjonctif"],
    faqs: standardFaqs("Cartalax"),
    references: [pubmedSearch("cartalax peptide bioregulator")],
  },
  {
    slug: "cardiogen", name: "Cardiogen", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Bioregulateur peptidique étudié dans le tissu cardiaque.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "20 mg", sku: "SKY-CARDIOGEN-20MG", price: 44.99 }],
    mechanism: "Le cardiogen est un peptide bioregulateur court étudié pour son influence sur l’expression génique dans des modèles de tissu myocardique.",
    researchAreas: ["Bioregulateurs peptidiques", "Expression génique cardiaque", "Modèles tissulaires"],
    faqs: standardFaqs("Cardiogen"),
    references: [pubmedSearch("cardiogen peptide bioregulator")],
  },
  {
    slug: "cortagen", name: "Cortagen", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Bioregulateur peptidique étudié dans le tissu nerveux périphérique.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "20 mg", sku: "SKY-CORTAGEN-20MG", price: 44.99 }],
    mechanism: "Le cortagen est un peptide bioregulateur court étudié dans les modèles de régénération du tissu nerveux périphérique.",
    researchAreas: ["Bioregulateurs peptidiques", "Régénération nerveuse", "Expression génique tissulaire"],
    faqs: standardFaqs("Cortagen"),
    references: [pubmedSearch("cortagen peptide bioregulator")],
  },
  {
    slug: "bronchogen", name: "Bronchogen", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Bioregulateur peptidique étudié dans le tissu bronchopulmonaire.",
    synonyms: ["Ala-Asp-Glu-Leu"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "20 mg", sku: "SKY-BRONCHOGEN-20MG", price: 44.99 }],
    mechanism: "Le bronchogen est un tétrapeptide bioregulateur étudié pour son influence sur l’expression génique dans les modèles de tissu bronchique.",
    researchAreas: ["Bioregulateurs peptidiques", "Tissu bronchopulmonaire", "Expression génique tissulaire"],
    faqs: standardFaqs("Bronchogen"),
    references: [pubmedSearch("bronchogen peptide")],
  },
  {
    slug: "ara-290", name: "ARA-290 (Cibinétide)", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Peptide dérivé de l’EPO ciblant le récepteur innate repair, sans effet érythropoïétique.",
    synonyms: ["Cibinetide"], cas: '1208243-50-8', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-ARA-290-10MG", price: 79.99 }, { label: "16 mg", sku: "SKY-ARA-290-16MG", price: 114.99 }],
    mechanism: "L’ARA-290 reprend une séquence de l’érythropoïétine et active le récepteur « innate repair » (IRR) impliqué dans la protection tissulaire et l’inflammation, sans stimuler l’érythropoïèse.",
    researchAreas: ["Récepteur innate repair (IRR)", "Neuroprotection et inflammation", "Peptides dérivés de l’EPO"],
    faqs: standardFaqs("ARA-290 (Cibinétide)"),
    references: [pubmedSearch("ARA-290 cibinetide")],
  },
  {
    slug: "ptd-dbm", name: "PTD-DBM", category: "recherche-tissulaire", format: "lyophilise",
    summary: "Peptide inhibiteur de l’interaction CXXC5-Dishevelled, étudié dans la voie Wnt.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "1 mg", sku: "SKY-PTD-DBM-1MG", price: 59.99 }],
    mechanism: "Le PTD-DBM inhibe l’interaction CXXC5-Dishevelled, levant un frein de la voie Wnt/β-caténine dans des modèles de régénération (follicule pileux, cicatrisation).",
    researchAreas: ["Voie Wnt / β-caténine", "Interaction CXXC5-Dishevelled", "Modèles de régénération"],
    faqs: standardFaqs("PTD-DBM"),
    references: [pubmedSearch("PTD-DBM CXXC5 Wnt")],
  },
  {
    slug: "selank", name: "Selank", category: "nootropiques", format: "lyophilise",
    summary: "Analogue synthétique de la tuftsine, étudié dans la régulation du stress et l’immunomodulation.",
    synonyms: ["TP-7"], cas: '129954-34-3', formula: 'C33H57N11O9', molarMass: 751.87, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-SELANK-5MG", price: 44.99 }, { label: "10 mg", sku: "SKY-SELANK-10MG", price: 64.99 }],
    mechanism: "Selank prolonge la tuftsine par un motif Pro-Gly-Pro. Il est étudié pour son influence sur l’expression de gènes du système GABAergique et sur certaines cytokines.",
    researchAreas: ["Expression génique (système GABAergique)", "Immunomodulation et cytokines", "Modèles précliniques de stress"],
    faqs: standardFaqs("Selank"),
    references: [pubmedSearch("Selank"), pubchemSearch("Selank")],
  },
  {
    slug: "semax", name: "Semax", category: "nootropiques", format: "lyophilise",
    summary: "Analogue du fragment ACTH (4-10), étudié dans la neuroprotection et l’expression des neurotrophines.",
    synonyms: ["ACTH (4-7) Pro-Gly-Pro"], cas: '80714-61-0', formula: 'C37H51N9O10S', molarMass: 813.93, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-SEMAX-5MG", price: 44.99 }, { label: "10 mg", sku: "SKY-SEMAX-10MG", price: 64.99 }],
    mechanism: "Semax associe le fragment ACTH (4-7) à un motif Pro-Gly-Pro qui ralentit sa dégradation. Il est étudié pour son influence sur l’expression du BDNF et dans des modèles d’ischémie.",
    researchAreas: ["Expression du BDNF", "Modèles précliniques d’ischémie", "Stabilité des peptides par motif PGP"],
    faqs: standardFaqs("Semax"),
    references: [pubmedSearch("Semax peptide"), pubchemSearch("Semax")],
  },
  {
    slug: "dsip", name: "DSIP", category: "nootropiques", format: "lyophilise",
    summary: "Peptide induisant le sommeil delta, étudié dans la régulation du sommeil et du stress.",
    synonyms: ["Delta sleep-inducing peptide"], cas: '62568-57-4', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-DSIP-2MG", price: 49.99 }, { label: "5 mg", sku: "SKY-DSIP-5MG", price: 59.99 }, { label: "10 mg", sku: "SKY-DSIP-10MG", price: 74.99 }],
    mechanism: "Le DSIP est un nonapeptide étudié pour son influence sur l’architecture du sommeil à ondes lentes et la modulation neuro-endocrine.",
    researchAreas: ["Sommeil à ondes lentes", "Modulation neuro-endocrine", "Réponse au stress"],
    faqs: standardFaqs("DSIP"),
    references: [pubmedSearch("delta sleep inducing peptide")],
  },
  {
    slug: "cerebrolysin", name: "Cerebrolysin", category: "nootropiques", format: "solution",
    summary: "Mélange de peptides neurotrophiques d’origine porcine, étudié en neuroprotection.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "Qualité laboratoire", appearance: "Solution limpide", storage: SOL,
    variants: [{ label: "60 mg", sku: "SKY-CEREBROLYSIN-60MG", price: 45.0 }],
    mechanism: "Le cérébrolysine est un mélange standardisé de peptides à bas poids moléculaire étudié pour son activité neurotrophique dans des modèles de lésion neuronale.",
    researchAreas: ["Activité neurotrophique", "Modèles de lésion neuronale", "Plasticité synaptique"],
    faqs: standardFaqs("Cerebrolysin"),
    references: [pubmedSearch("cerebrolysin neurotrophic")],
  },
  {
    slug: "pinealon", name: "Pinealon", category: "nootropiques", format: "lyophilise",
    summary: "Tripeptide bioregulateur (EDR), étudié dans la protection neuronale.",
    synonyms: ["Glu-Asp-Arg"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-PINEALON-5MG", price: 44.99 }, { label: "10 mg", sku: "SKY-PINEALON-10MG", price: 65.0 }],
    mechanism: "Le pinealon est un tripeptide court qui pénètre le noyau et est étudié pour son influence sur l’expression génique neuronale et la résistance au stress oxydatif.",
    researchAreas: ["Bioregulateurs peptidiques courts", "Expression génique neuronale", "Stress oxydatif"],
    faqs: standardFaqs("Pinealon"),
    references: [pubmedSearch("pinealon peptide")],
  },
  {
    slug: "dermorphin", name: "Dermorphin", category: "nootropiques", format: "lyophilise",
    summary: "Heptapeptide opioïde naturel, agoniste puissant des récepteurs mu, réactif de recherche.",
    synonyms: [], cas: '77614-16-5', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-DERMORPHIN-2MG", price: 49.99 }, { label: "10 mg", sku: "SKY-DERMORPHIN-10MG", price: 99.99 }],
    mechanism: "La dermorphine est un peptide opioïde contenant un acide aminé D, agoniste sélectif du récepteur mu. Réactif utilisé dans l’étude de la signalisation opioïde in vitro.",
    researchAreas: ["Récepteur opioïde mu", "Acides aminés D et stabilité", "Signalisation opioïde"],
    faqs: standardFaqs("Dermorphin"),
    references: [pubmedSearch("dermorphin mu opioid")],
  },
  {
    slug: "orexin-a", name: "Orexin A", category: "nootropiques", format: "lyophilise",
    summary: "Neuropeptide hypothalamique régulant l’éveil, étudié via les récepteurs OX1R/OX2R.",
    synonyms: ["Hypocrétine-1"], cas: '205640-90-0', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-OREXIN-A-10MG", price: 109.99 }],
    mechanism: "L’orexine A active les récepteurs OX1R et OX2R et régule l’éveil, l’appétit et la dépense énergétique dans des modèles neuronaux.",
    researchAreas: ["Récepteurs OX1R / OX2R", "Régulation de l’éveil", "Signalisation hypothalamique"],
    faqs: standardFaqs("Orexin A"),
    references: [pubmedSearch("orexin A hypocretin")],
  },
  {
    slug: "orexin-b", name: "Orexin B", category: "nootropiques", format: "lyophilise",
    summary: "Neuropeptide hypothalamique, agoniste préférentiel d’OX2R, régulateur de l’éveil.",
    synonyms: ["Hypocrétine-2"], cas: '205640-91-1', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-OREXIN-B-5MG", price: 89.99 }, { label: "10 mg", sku: "SKY-OREXIN-B-10MG", price: 139.99 }],
    mechanism: "L’orexine B active préférentiellement le récepteur OX2R et participe à la régulation de l’éveil et de l’homéostasie énergétique dans les modèles neuronaux.",
    researchAreas: ["Récepteur OX2R", "Régulation de l’éveil", "Signalisation hypothalamique"],
    faqs: standardFaqs("Orexin B"),
    references: [pubmedSearch("orexin B hypocretin")],
  },
  {
    slug: "epithalon", name: "Épithalon", category: "longevite", format: "lyophilise",
    summary: "Tétrapeptide synthétique (AEDG), étudié dans la télomérase et le vieillissement cellulaire.",
    synonyms: ["Epitalon", "AEDG"], cas: '307297-39-8', formula: 'C14H22N4O9', molarMass: 390.35, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-EPITHALON-10MG", price: 59.99 }, { label: "50 mg", sku: "SKY-EPITHALON-50MG", price: 139.99 }],
    mechanism: "L’épithalon est étudié pour son influence sur l’activité de la télomérase et l’expression génique en culture. Le niveau de preuve reste limité.",
    researchAreas: ["Activité de la télomérase", "Sénescence réplicative en culture", "Rythmes circadiens en modèle animal"],
    faqs: standardFaqs("Épithalon"),
    references: [pubmedSearch("epitalon telomerase"), pubchemSearch("epitalon")],
  },
  {
    slug: "nad-plus", name: "NAD+", category: "longevite", format: "lyophilise",
    summary: "Coenzyme central du métabolisme redox, substrat des sirtuines et des PARP.",
    synonyms: ["β-Nicotinamide adénine dinucléotide"], cas: '53-84-9', formula: 'C21H27N7O14P2', molarMass: 663.43, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "100 mg", sku: "SKY-NAD-PLUS-100MG", price: 34.99 }, { label: "500 mg", sku: "SKY-NAD-PLUS-500MG", price: 65.99 }, { label: "1000 mg", sku: "SKY-NAD-PLUS-1000MG", price: 89.99 }],
    mechanism: "Le NAD+ est l’accepteur d’électrons de nombreuses déshydrogénases et le substrat des sirtuines, PARP et CD38. Outil d’étude du lien entre état énergétique et signalisation.",
    researchAreas: ["Activité des sirtuines et des PARP", "Bioénergétique mitochondriale", "Métabolisme du NAD+ et vieillissement"],
    faqs: standardFaqs("NAD+"),
    references: [pubmedSearch("NAD+ sirtuins aging"), pubchemSearch("NAD+")],
  },
  {
    slug: "mots-c", name: "MOTS-c", category: "longevite", format: "lyophilise",
    summary: "Peptide d’origine mitochondriale de 16 acides aminés, étudié dans le métabolisme et le stress.",
    synonyms: ["MOTS-c (Human)"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-MOTS-C-10MG", price: 54.99 }, { label: "20 mg", sku: "SKY-MOTS-C-20MG", price: 89.99 }, { label: "40 mg", sku: "SKY-MOTS-C-40MG", price: 134.99 }],
    mechanism: "MOTS-c est codé par le génome mitochondrial. Il est étudié pour son action sur l’AMPK, le métabolisme du folate et la translocation nucléaire en stress métabolique.",
    researchAreas: ["Communication mitochondrie-noyau", "Activation de l’AMPK", "Modèles de stress métabolique"],
    faqs: standardFaqs("MOTS-c"),
    references: [pubmedSearch("MOTS-c mitochondrial peptide")],
    featured: true,
  },
  {
    slug: "ss-31", name: "SS-31 (Élamiprétide)", category: "longevite", format: "lyophilise",
    summary: "Peptide ciblant la cardiolipine mitochondriale, étudié en bioénergétique.",
    synonyms: ["Elamipretide", "MTP-131"], cas: '736992-21-5', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-SS-31-5MG", price: 54.99 }, { label: "10 mg", sku: "SKY-SS-31-10MG", price: 89.99 }, { label: "50 mg", sku: "SKY-SS-31-50MG", price: 199.99 }],
    mechanism: "Le SS-31 se lie à la cardiolipine de la membrane mitochondriale interne et est étudié pour son influence sur l’efficacité de la chaîne respiratoire et le stress oxydatif.",
    researchAreas: ["Cardiolipine mitochondriale", "Chaîne respiratoire", "Stress oxydatif"],
    faqs: standardFaqs("SS-31 (Élamiprétide)"),
    references: [pubmedSearch("elamipretide SS-31 cardiolipin")],
  },
  {
    slug: "humanin", name: "Humanin", category: "longevite", format: "lyophilise",
    summary: "Peptide mitochondrial cytoprotecteur, étudié dans la survie cellulaire.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-HUMANIN-10MG", price: 69.99 }],
    mechanism: "L’humanine est un peptide dérivé du génome mitochondrial étudié pour son action cytoprotectrice via les récepteurs de type gp130 dans des modèles de stress cellulaire.",
    researchAreas: ["Peptides mitochondriaux", "Cytoprotection (voie gp130)", "Survie cellulaire"],
    faqs: standardFaqs("Humanin"),
    references: [pubmedSearch("humanin mitochondrial peptide")],
  },
  {
    slug: "fox04-dri", name: "FOXO4-DRI", category: "longevite", format: "lyophilise",
    summary: "Peptide senolytique perturbant l’interaction FOXO4-p53, étudié dans la sénescence.",
    synonyms: ["FOXO4 D-Retro-Inverso"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-FOX04-DRI-2MG", price: 89.99 }, { label: "10 mg", sku: "SKY-FOX04-DRI-10MG", price: 249.99 }],
    mechanism: "Le FOXO4-DRI est un peptide D-retro-inverso qui perturbe l’interaction FOXO4-p53 et est étudié pour l’élimination sélective des cellules sénescentes in vitro.",
    researchAreas: ["Interaction FOXO4-p53", "Sénescence cellulaire", "Approches senolytiques"],
    faqs: standardFaqs("FOXO4-DRI"),
    references: [pubmedSearch("FOXO4-DRI senescence")],
  },
  {
    slug: "kisspeptin-10", name: "Kisspeptin-10", category: "longevite", format: "lyophilise",
    summary: "Fragment actif de la kisspeptine, régulateur de l’axe gonadotrope.",
    synonyms: [], cas: '374675-21-5', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-KISSPEPTIN-10-5MG", price: 59.99 }, { label: "10 mg", sku: "SKY-KISSPEPTIN-10-10MG", price: 94.99 }],
    mechanism: "La kisspeptine-10 active le récepteur KISS1R et stimule la libération de GnRH dans les modèles d’étude de l’axe hypothalamo-hypophyso-gonadique.",
    researchAreas: ["Récepteur KISS1R", "Libération de GnRH", "Axe gonadotrope"],
    faqs: standardFaqs("Kisspeptin-10"),
    references: [pubmedSearch("kisspeptin-10 KISS1R")],
  },
  {
    slug: "gonadorelin", name: "Gonadorelin Acetate", category: "longevite", format: "lyophilise",
    summary: "GnRH synthétique, réactif d’étude de l’axe hypophyso-gonadique.",
    synonyms: ["GnRH"], cas: '33515-09-2', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-GONADORELIN-2MG", price: 39.99 }, { label: "5 mg", sku: "SKY-GONADORELIN-5MG", price: 59.99 }],
    mechanism: "La gonadoréline est la forme synthétique du GnRH qui active le récepteur GnRHR et stimule la sécrétion de LH et FSH dans les modèles d’étude de l’axe gonadotrope.",
    researchAreas: ["Récepteur GnRHR", "Sécrétion de LH / FSH", "Axe hypophyso-gonadique"],
    faqs: standardFaqs("Gonadorelin Acetate"),
    references: [pubmedSearch("gonadorelin GnRH")],
  },
  {
    slug: "triptorelin", name: "Triptorelin Acetate", category: "longevite", format: "lyophilise",
    summary: "Agoniste du GnRH à longue durée d’action, réactif de recherche endocrinienne.",
    synonyms: [], cas: '57773-63-4', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "2 mg", sku: "SKY-TRIPTORELIN-2MG", price: 49.99 }],
    mechanism: "La triptoréline est un agoniste puissant du GnRH qui, après stimulation initiale, désensibilise le récepteur GnRHR, un mécanisme étudié dans la régulation de l’axe gonadotrope.",
    researchAreas: ["Récepteur GnRHR", "Désensibilisation du récepteur", "Axe gonadotrope"],
    faqs: standardFaqs("Triptorelin Acetate"),
    references: [pubmedSearch("triptorelin GnRH agonist")],
  },
  {
    slug: "pt-141", name: "PT-141", category: "longevite", format: "lyophilise",
    summary: "Analogue de l’α-MSH (bremélanotide), agoniste des récepteurs à la mélanocortine.",
    synonyms: ["Bremélanotide"], cas: '189691-06-3', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-PT-141-10MG", price: 59.99 }],
    mechanism: "Le PT-141 active les récepteurs à la mélanocortine MC3R/MC4R, une voie étudiée dans la signalisation centrale de la fonction sexuelle et de l’appétit.",
    researchAreas: ["Récepteurs MC3R / MC4R", "Signalisation centrale", "Système mélanocortine"],
    faqs: standardFaqs("PT-141"),
    references: [pubmedSearch("bremelanotide PT-141 melanocortin")],
  },
  {
    slug: "melatonin", name: "Mélatonine", category: "longevite", format: "lyophilise",
    summary: "Hormone circadienne, réactif d’étude des rythmes et du stress oxydatif.",
    synonyms: [], cas: '73-31-4', formula: 'C13H16N2O2', molarMass: 232.28, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-MELATONIN-10MG", price: 29.99 }],
    mechanism: "La mélatonine active les récepteurs MT1/MT2 et agit comme piégeur de radicaux libres. Réactif d’étude des rythmes circadiens et du stress oxydatif.",
    researchAreas: ["Récepteurs MT1 / MT2", "Rythmes circadiens", "Stress oxydatif"],
    faqs: standardFaqs("Mélatonine"),
    references: [pubchemSearch("melatonin")],
  },
  {
    slug: "epo", name: "EPO (Érythropoïétine)", category: "longevite", format: "lyophilise",
    summary: "Érythropoïétine recombinante. Référence réglementée, étudiée dans la signalisation du récepteur de l’EPO.",
    synonyms: [], cas: '113427-24-0', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "3000 iu", sku: "SKY-EPO-3000IU", price: 50.0 }],
    mechanism: "L’EPO active le récepteur EPOR et la voie JAK2/STAT5, étudiée dans l’érythropoïèse et la protection tissulaire. Produit réglementé et classé comme agent dopant.",
    researchAreas: ["Récepteur de l’EPO (EPOR)", "Voie JAK2/STAT5", "Érythropoïèse"],
    faqs: standardFaqs("EPO (Érythropoïétine)"),
    references: [pubmedSearch("erythropoietin EPOR JAK2")],
    regulated: true,
  },
  {
    slug: "ghk-cu", name: "GHK-Cu", category: "skin-science", format: "lyophilise",
    summary: "Complexe cuivre du tripeptide Gly-His-Lys, étudié dans la matrice extracellulaire et les modèles cutanés.",
    synonyms: ["Copper tripeptide-1"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "50 mg", sku: "SKY-GHK-CU-50MG", price: 39.99 }, { label: "100 mg", sku: "SKY-GHK-CU-100MG", price: 60.99 }],
    mechanism: "Le GHK présente une forte affinité pour le cuivre(II). Le complexe est étudié pour son influence sur l’expression de gènes de la matrice (collagène, décorine) dans des modèles de fibroblastes.",
    researchAreas: ["Synthèse de collagène par les fibroblastes", "Remodelage de la matrice extracellulaire", "Formulation cosmétique et stabilité"],
    faqs: standardFaqs("GHK-Cu"),
    references: [pubmedSearch("GHK-Cu copper peptide"), pubchemSearch("GHK-Cu")],
    featured: true,
  },
  {
    slug: "ahk-cu", name: "AHK-Cu", category: "skin-science", format: "lyophilise",
    summary: "Complexe cuivre du tripeptide Ala-His-Lys, étudié dans le follicule pileux et la matrice.",
    synonyms: ["Copper tripeptide"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "50 mg", sku: "SKY-AHK-CU-50MG", price: 39.99 }, { label: "100 mg", sku: "SKY-AHK-CU-100MG", price: 60.99 }],
    mechanism: "L’AHK-Cu est un tripeptide complexé au cuivre étudié pour son influence sur les cellules du follicule pileux et l’expression de facteurs de croissance (VEGF) en culture.",
    researchAreas: ["Papille dermique et follicule pileux", "Expression du VEGF", "Formulation cosmétique"],
    faqs: standardFaqs("AHK-Cu"),
    references: [pubmedSearch("AHK-Cu copper peptide hair")],
  },
  {
    slug: "matrixyl", name: "Matrixyl", category: "skin-science", format: "lyophilise",
    summary: "Peptide signal pro-matrice (palmitoyl pentapeptide), étudié dans la synthèse de collagène.",
    synonyms: ["Palmitoyl pentapeptide-4"], cas: '214047-00-4', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-MATRIXYL-10MG", price: 44.99 }],
    mechanism: "Le Matrixyl est un peptide signal qui stimule l’expression du collagène et de la fibronectine par les fibroblastes dans les modèles cutanés et les formulations cosmétiques.",
    researchAreas: ["Synthèse de collagène et fibronectine", "Fibroblastes dermiques", "Formulation cosmétique"],
    faqs: standardFaqs("Matrixyl"),
    references: [pubmedSearch("matrixyl palmitoyl pentapeptide collagen")],
  },
  {
    slug: "snap-8", name: "SNAP-8", category: "skin-science", format: "lyophilise",
    summary: "Octapeptide mimétique de la SNAP-25, étudié dans la libération de neurotransmetteurs.",
    synonyms: ["Acétyl octapeptide-3"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-SNAP-8-10MG", price: 39.99 }, { label: "100 mg", sku: "SKY-SNAP-8-100MG", price: 199.99 }],
    mechanism: "Le SNAP-8 reproduit une séquence N-terminale de la SNAP-25 et entre en compétition dans la formation du complexe SNARE, étudié dans des modèles d’exocytose et en cosmétique.",
    researchAreas: ["Complexe SNARE et exocytose", "Formulation dermo-cosmétique", "Tests de stabilité en émulsion"],
    faqs: standardFaqs("SNAP-8"),
    references: [pubmedSearch("acetyl octapeptide-3 SNAP-8")],
    isNew: true,
  },
  {
    slug: "melanotan-1", name: "Melanotan I", category: "skin-science", format: "lyophilise",
    summary: "Analogue de l’α-MSH (afamélanotide), agoniste des récepteurs à la mélanocortine, étudié en pigmentation.",
    synonyms: ["Afamélanotide", "MT-1"], cas: '75921-69-6', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-MELANOTAN-1-10MG", price: 55.99 }],
    mechanism: "Le Melanotan I active le récepteur MC1R des mélanocytes et stimule la mélanogenèse dans les modèles de pigmentation cutanée.",
    researchAreas: ["Récepteur MC1R", "Mélanogenèse", "Modèles de pigmentation"],
    faqs: standardFaqs("Melanotan I"),
    references: [pubmedSearch("afamelanotide melanotan melanocortin")],
  },
  {
    slug: "melanotan-2", name: "Melanotan II", category: "skin-science", format: "lyophilise",
    summary: "Analogue cyclique de l’α-MSH, agoniste large des mélanocortines, réactif de pigmentation.",
    synonyms: ["MT-2"], cas: '121062-08-6', formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "10 mg", sku: "SKY-MELANOTAN-2-10MG", price: 60.99 }],
    mechanism: "Le Melanotan II est un analogue cyclique non sélectif des récepteurs à la mélanocortine (MC1R, MC3R, MC4R), étudié dans la mélanogenèse et la signalisation centrale.",
    researchAreas: ["Récepteurs à la mélanocortine", "Mélanogenèse", "Signalisation MC4R"],
    faqs: standardFaqs("Melanotan II"),
    references: [pubmedSearch("melanotan II melanocortin")],
  },
  {
    slug: "kpv", name: "KPV", category: "skin-science", format: "lyophilise",
    summary: "Tripeptide C-terminal de l’α-MSH (Lys-Pro-Val), étudié pour la modulation de l’inflammation.",
    synonyms: ["Lys-Pro-Val"], cas: '67727-97-3', formula: 'C16H30N4O4', molarMass: 342.43, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "5 mg", sku: "SKY-KPV-5MG", price: 39.99 }, { label: "10 mg", sku: "SKY-KPV-10MG", price: 59.99 }],
    mechanism: "Le KPV est étudié pour son action sur la voie NF-κB et la production de cytokines pro-inflammatoires dans des modèles épithéliaux et immunitaires.",
    researchAreas: ["Signalisation NF-κB", "Modèles d’inflammation épithéliale", "Production de cytokines in vitro"],
    faqs: standardFaqs("KPV"),
    references: [pubmedSearch("KPV tripeptide inflammation")],
  },
  {
    slug: "glow", name: "GLOW (BPC-157 + GHK-Cu + TB-500)", category: "skin-science", format: "lyophilise",
    summary: "Association de trois peptides de réparation et de matrice, étudiée pour ses effets combinés.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "70 mg", sku: "SKY-GLOW-70MG", price: 109.99 }],
    mechanism: "Le GLOW combine BPC-157, GHK-Cu et TB-500. Association étudiée dans les modèles combinant réparation tissulaire, angiogenèse et synthèse de matrice.",
    researchAreas: ["Combinaisons de peptides", "Réparation et matrice extracellulaire", "Modèles cutanés"],
    faqs: standardFaqs("GLOW (BPC-157 + GHK-Cu + TB-500)"),
    references: [pubmedSearch("BPC-157 GHK-Cu TB-500")],
  },
  {
    slug: "klow", name: "KLOW (BPC-157 + GHK-Cu + TB-500 + KPV)", category: "skin-science", format: "lyophilise",
    summary: "Association de quatre peptides de réparation, de matrice et anti-inflammatoire.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "80 mg", sku: "SKY-KLOW-80MG", price: 139.99 }],
    mechanism: "Le KLOW ajoute le KPV à l’association GLOW. Étudié dans les modèles combinant réparation, matrice extracellulaire et modulation de l’inflammation.",
    researchAreas: ["Combinaisons de peptides", "Réparation et inflammation", "Modèles cutanés"],
    faqs: standardFaqs("KLOW (BPC-157 + GHK-Cu + TB-500 + KPV)"),
    references: [pubmedSearch("BPC-157 GHK-Cu TB-500 KPV")],
  },
  {
    slug: "hcg", name: "HCG", category: "myo-science", format: "lyophilise",
    summary: "Gonadotrophine chorionique humaine recombinante. Référence réglementée, disponible uniquement sur devis.",
    synonyms: ["Gonadotrophine chorionique"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "1000 iu", sku: "SKY-HCG-1000IU", price: 0 }, { label: "5000 iu", sku: "SKY-HCG-5000IU", price: 0 }, { label: "10000 iu", sku: "SKY-HCG-10000IU", price: 0 }],
    mechanism: "L’HCG active le récepteur LH/CG et la stéroïdogenèse, étudiée dans l’axe gonadotrope. Produit pharmaceutique strictement réglementé.",
    researchAreas: ["Récepteur LH/CG", "Stéroïdogenèse", "Axe gonadotrope"],
    faqs: standardFaqs("HCG"),
    references: [pubmedSearch("human chorionic gonadotropin LHCGR")],
    regulated: true, quoteOnly: true,
  },
  {
    slug: "hmg", name: "HMG", category: "myo-science", format: "lyophilise",
    summary: "Gonadotrophine ménopausique humaine. Référence réglementée, disponible uniquement sur devis.",
    synonyms: ["Ménotropine"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "75 iu", sku: "SKY-HMG-75IU", price: 0 }],
    mechanism: "L’HMG apporte une activité FSH et LH, étudiée dans la folliculogenèse et la stéroïdogenèse. Produit pharmaceutique strictement réglementé.",
    researchAreas: ["Activité FSH / LH", "Folliculogenèse", "Axe gonadotrope"],
    faqs: standardFaqs("HMG"),
    references: [pubmedSearch("human menopausal gonadotropin")],
    regulated: true, quoteOnly: true,
  },
  {
    slug: "botulinum-toxin", name: "Toxine botulique (type A)", category: "skin-science", format: "lyophilise",
    summary: "Neurotoxine réglementée. Référence documentaire, non vendue en ligne : uniquement sur devis à des structures autorisées.",
    synonyms: ["Botulinum toxin type A"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "≥ 98 % (HPLC), identité confirmée par MS", appearance: "Poudre lyophilisée", storage: LYO,
    variants: [{ label: "100 iu", sku: "SKY-BOTULINUM-TOXIN-100IU", price: 0 }],
    mechanism: "La toxine botulique de type A clive la protéine SNAP-25 et bloque la libération d’acétylcholine à la jonction neuromusculaire. Substance strictement réglementée et contrôlée.",
    researchAreas: ["Clivage de la SNAP-25", "Jonction neuromusculaire", "Complexe SNARE"],
    faqs: standardFaqs("Toxine botulique (type A)"),
    references: [pubmedSearch("botulinum toxin SNAP-25")],
    regulated: true, quoteOnly: true,
  },
  {
    slug: "bac-water", name: "Eau bactériostatique", category: "consommables", format: "consommable",
    summary: "Eau stérile à 0,9 % d’alcool benzylique, pour la reconstitution des peptides lyophilisés.",
    synonyms: ["BAC Water"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "Qualité laboratoire", appearance: "Consommable de laboratoire", storage: "Température ambiante, à l’abri de la lumière.",
    variants: [{ label: "3 ml", sku: "SKY-BAC-WATER-3ML", price: 7.9 }, { label: "10 ml", sku: "SKY-BAC-WATER-10ML", price: 14.9 }],
    mechanism: "L’alcool benzylique limite la croissance bactérienne lors des prélèvements successifs. Vérifier la compatibilité avec le protocole : certains peptides et lignées y sont sensibles.",
    researchAreas: ["Reconstitution de peptides lyophilisés", "Préparation de solutions mères"],
    faqs: [],
    references: [],
  },
  {
    slug: "acetic-acid", name: "Acide acétique 0,6 %", category: "consommables", format: "consommable",
    summary: "Solvant stérile pour la reconstitution des peptides peu solubles dans l’eau.",
    synonyms: ["醋酸水"], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "Qualité laboratoire", appearance: "Consommable de laboratoire", storage: "Température ambiante, à l’abri de la lumière.",
    variants: [{ label: "3 ml", sku: "SKY-ACETIC-ACID-3ML", price: 8.9 }, { label: "10 ml", sku: "SKY-ACETIC-ACID-10ML", price: 12.9 }],
    mechanism: "Une solution acide diluée améliore la solubilité des peptides basiques ou hydrophobes. Ajuster ensuite le pH selon les besoins de l’essai.",
    researchAreas: ["Reconstitution de peptides basiques", "Solutions mères"],
    faqs: [],
    references: [],
  },
  {
    slug: "wipes", name: "Lingettes alcoolisées", category: "consommables", format: "consommable",
    summary: "Lingettes imbibées d’isopropanol 70 %, pour la désinfection du septum et du plan de travail.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "Qualité laboratoire", appearance: "Consommable de laboratoire", storage: "Température ambiante, à l’abri de la lumière.",
    variants: [{ label: "Pack de 10", sku: "SKY-WIPES-PACKDE10", price: 2.99 }],
    mechanism: "Désinfection du bouchon des flacons et du plan de travail avant prélèvement, pour préserver la stérilité des solutions mères.",
    researchAreas: ["Asepsie du plan de travail", "Préparation des flacons"],
    faqs: [],
    references: [],
  },
  {
    slug: "syringes-1ml", name: "Seringues 1 ml", category: "consommables", format: "consommable",
    summary: "Seringues stériles graduées 1 ml pour la manipulation précise des solutions au laboratoire.",
    synonyms: [], cas: null, formula: null, molarMass: null, pubchem: null,
    purity: "Qualité laboratoire", appearance: "Consommable de laboratoire", storage: "Température ambiante, à l’abri de la lumière.",
    variants: [{ label: "Pack de 10", sku: "SKY-SYRINGES-1ML-PACKDE10", price: 5.0 }],
    mechanism: "Seringues graduées à usage unique pour le prélèvement et la dilution précis des solutions de peptides au laboratoire.",
    researchAreas: ["Prélèvement et dilution", "Précision de pipetage"],
    faqs: [],
    references: [],
  },
];

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);
export const getCategory = (slug: string) => categories.find((c) => c.slug === slug);
export const productsByCategory = (slug: CategorySlug) => products.filter((p) => p.category === slug);
export const minPrice = (p: Product) => Math.min(...p.variants.map((v) => v.price));
export const isPurchasable = (p: Product) => !p.quoteOnly && p.variants.some((v) => v.price > 0);

// Supplements proposes sur les fiches peptides (vente additionnelle).
export const addOnSlugs = ["bac-water", "wipes", "syringes-1ml"];

export type Batch = { sku: string; lot: string; date: string; purity: string | null; coaUrl: string | null; sdsUrl: string | null };
export const batches: Batch[] = products.flatMap((p) =>
  p.variants.map((v) => ({ sku: v.sku, lot: `${v.sku.replace("SKY-", "")}-A01`, date: "", purity: null, coaUrl: null, sdsUrl: null })),
);
export const batchFor = (sku: string) => batches.find((b) => b.sku === sku);
